source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'GymRats' do
    pod 'Alamofire', '~> 4.7'
    pod 'RxSwift',    '~> 4.0'
    pod 'RxCocoa',    '~> 4.0'
    pod 'RxAlamofire'
    pod 'Kingfisher', '~> 4.0'
    pod 'RxOptional'
    pod 'YogaKit'
    pod 'MMDrawerController', '~> 0.5.7'
    pod 'SwiftDate', '~> 5.0'
    pod "AvatarImageView", '~> 2.2.0'
    pod 'CVCalendar', '~> 1.6.2'
    pod 'GradientLoadingBar', '~> 1.0'
    pod 'Eureka'
    pod "RxEureka", "~> 0.2"
    pod 'Firebase/Core'
    pod 'Firebase/Storage'
    pod 'Cache'
    pod 'Fabric', '~> 1.9.0'
    pod 'Crashlytics', '~> 3.12.0'
    pod 'GooglePlaces'
    pod 'TTTAttributedLabel'
    pod 'EasyNotificationBadge'
    pod 'MessageKit'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            if target.name == 'Cache'
                config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-Onone'
            end
	    if target.name == "YogaKit"
		config.build_settings['SWIFT_VERSION'] = '4.0'
	    end
        end
    end
end
