source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'GymRats' do
    pod 'Alamofire', '~> 4.7'
    pod 'RxSwift',    '~> 4.0'
    pod 'RxCocoa',    '~> 4.0'
    pod 'RxAlamofire'
    pod 'Kingfisher', '~> 4.0'
    pod 'RxOptional'
    pod 'FlexLayout'
    pod 'YogaKit'
    pod 'SkyFloatingLabelTextField', '~> 3.0'
end
